### PR TITLE
use HTTPS URL for cloning GitHub

### PR DESCRIPTION
**Pull request by julianladisch**
recommended by https://help.github.com/articles/which-remote-url-should-i-use/

### CODE REVIEW

**Comment by MikeTaylor** [comment]
I'm not sure about this change. Remember this document is basically for
developers, who are likely going to want to commit changes.

-- Mike.

**Comment by nassibnassar** [comment]
The document appears to me like it's about fetching, building, and running the code in general; are you saying it's for the committers who merge changes directly into the repository?

**Comment by MikeTaylor** [comment]
I think that is who, in practice, is likely to use it.

-- Mike.

**Comment by heikkilevanto** [comment]
This is a document, so it could as well mention both https and ssh methods for cloning when the issue first comes up, and thereafter use which ever looks nicer. The kind of developers that read this document can change the command line as needed.

**Comment by MikeTaylor** [comment]
Fair point.

**Comment by nassibnassar** [comment]
I don't know, but my guess is that it will be read and used by far more non-committers than committers.

**Comment by julianladisch** [comment]
I've always used HTTPS URLs and never had any problems pushing commits to GitHub.

**Pull request closed without merging**
